export enum TemplateEnum {
  CONFIRM_EMAIL,
  CREATE_ORDER,
  CREATE_ADMIN,
  SUCCESSFUL_CREATE_ADMIN,
  FORGOT_PASSWORD,
  SUCCESSFUL_CHANGE_PASSWORD,
  INVITATION_WORKER,
  REMPLACEMENT_NOTIFICATION,
  TRANSACTION_NOTIFICATION,
}
